spring:
  datasource:
    url: jdbc:h2:file:./data/empDb
    username: ${database.username}  # Added as environment variables
    password: ${database.password}  # Added as environment variables
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

